change solr version in dockerfile
scientist-softserv/oral-history pull request #27
Opened 2023-03-15 17:14 UTC by summer-cook

2023-03-17 21:43 UTC, orangewolf commented on solr/Dockerfile
> +FROM solr:8.1
this needs to be 8.11 I believe

2023-03-17 21:44 UTC, orangewolf requested changes
Not the right version to go to (8.11 is the only 8 version supported), also can you confirm this really works? we took solr down and brought the app up and imported some records with this setup?

2023-03-17 22:15 UTC, aprilrieger commented
> 
Yes here is my workflow for testing:

get `.env.development` here: https://start.1password.com/open/i?a=LTLZ652TT5H5FHMYMASSH7PIXM&v=huuakin4bu4xanlhktv42qheam&i=ok6rwracafccnhrhur7usyfwoi&h=scientist.1password.com

gem install stack_car -v0.16.0
gem install dory

dory up
sc build
sc up

navigate to `http://oralhistory.test/users/sign_in`
login: creds in the .env

navigate to `http://oralhistory.test/admin`

run importer OR run in web container `rake db:migrate import[10]` [#] <— amount of works you import

Need troubleshooting tips?
If you do a `dc down -v`, odds are you will want to do a `rm -rf tmp/*`

2023-03-17 22:24 UTC, orangewolf commented
if you open the solr admin interface does it show the solr 8 version? (just trying to be thorough)

2023-03-20 03:29 UTC, aprilrieger commented
documentation `ERROR: Error CREATEing SolrCore 'blacklight-core': Unable to create core [blacklight-core] Caused by: solr.StandardFilterFactory`: https://github.com/projectblacklight/blacklight/pull/2017/files

2023-03-21 00:17 UTC, aprilrieger commented
@orangewolf This is ready for re-review.

Note that I needed this PR merged into the branch for the linking to the correct field retriever on this [pr](https://github.com/scientist-softserv/oral-history/pull/31)
Demo video here: https://share.getcloudapp.com/L1uDJ0j5

2023-03-21 01:14 UTC, orangewolf approved these changes

2023-03-21 01:14 UTC, orangewolf commented
@aprilrieger good work!

2023-03-21 08:01 UTC, merged